### ISSUE TITLE
Inferring distance between points or lines

### ISSUE THREAD

**Issue by davidshumway** [galbiston/geosparql-jena#8]
Is it possible to create using RDF a relationship between points (Latitude/Longitude) such that when loaded into a store (such as Jena Fuseki with the GeoSPARQL extension) that the distance between points will be inferred, e.g. in kilometers?

Otherwise, in order to determine the distance between points and add it to the triple store, I imagine that a query would be necessary for each point (and/or a query with a subquery to essentially to run a query for all points in a single query). Does this sound correct?

Ideally, the solution is fast as there could be millions of points. For example, I tried measuring 600,000 points to 9,000 linestrings (600k x 9k comparisons) in Jena GeoSPARL Fuseki and each comparison was taking roughly 10 seconds.

**Comment by galbiston** [comment]
This throws up many questions about your use case. A general approach to adopt could be an [INSERT WHERE query](https://www.w3.org/TR/2013/REC-sparql11-update-20130321/#insert). You may find using a VALUES block and the [ParameterizedSparqlString](https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/query/ParameterizedSparqlString.html) useful.

In the WHERE body, the point can be defined and then the distance calculation performed against the linestrings in the dataset. These distance calculations can then be asserted into the graph using a set of statements to construct a relationship between the point, linestring and distance. This offline step would then result in a dataset that can be queried repeatedly and quickly for your needs online.

Optimising SPARQL queries is a topic in itself and depends on the data structures and queries being performed. The first step would be to reduce down the number of calculations by partitioning the search space in some way as otherwise you will be facing a combinatorial explosion when it is likely that most results are discarded.
